### ISSUE TITLE
sorry for creating issue i want to tell you that your webiste is nice but have issue of horizontal bar can i fix it 

### ISSUE THREAD

**Issue by Ayusht777** [ibelick/animation#1]
https://www.julienthibeaut.xyz/blog

**Comment by ibelick** [comment]
Hi, thanks for pointing that out! Could you let me know which browser and screen size you're using, and on which page you noticed the issue?

**Comment by Ayusht777** [comment]
Mozilla Firefox   version  118.02 desktop resolution 1920 * 1080 
![image](https://github.com/ibelick/animation/assets/106388215/2975d1a1-05b2-4900-9d00-0ee2f0d38c26)

**Comment by ibelick** [comment]
I just fixed it. Thanks :)

**Comment by Ayusht777** [comment]
it okay
